import { useCallback, useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { addPracticeNote, downloadDocument, getPractice, requestDocument, updateDocument, uploadDocument } from '../api/practices'
import { Badge } from '../components/common/Badge'
import { Button } from '../components/common/Button'
import { Card } from '../components/common/Card'
import { PageHeader } from '../components/common/PageHeader'
import { ErrorState } from '../components/feedback/ErrorState'
import { LoadingState } from '../components/feedback/LoadingState'
import { formatDateTime, humanize } from '../utils/formatters'

function DocumentRow({ document, onChanged }) {
  const [file, setFile] = useState(null); const [busy, setBusy] = useState(''); const [error, setError] = useState('')
  async function upload() { const allowed = ['application/pdf', 'image/jpeg', 'image/png']; if (!file || file.size > 10 * 1024 * 1024 || !allowed.includes(file.type)) { setError('Seleziona PDF, JPG o PNG fino a 10 MiB.'); return } setBusy('upload'); setError(''); try { await uploadDocument(document.id, file); setFile(null); await onChanged() } catch (e) { setError(e.message) } finally { setBusy('') } }
  async function status(value) { setBusy('status'); try { await updateDocument(document.id, { status: value }); await onChanged() } catch (e) { setError(e.message) } finally { setBusy('') } }
  async function download() { setBusy('download'); try { const blob = await downloadDocument(document.id); const url = URL.createObjectURL(blob); const anchor = window.document.createElement('a'); anchor.href = url; anchor.download = document.original_name || document.name; anchor.click(); URL.revokeObjectURL(url) } catch (e) { setError(e.message) } finally { setBusy('') } }
  return <article className="document-row"><div><strong>{document.name}</strong><Badge tone={document.status === 'verified' ? 'success' : document.status === 'rejected' ? 'danger' : 'blue'}>{humanize(document.status)}</Badge></div><p>{document.original_name || 'File non ancora caricato'}</p><div className="document-actions"><input aria-label={`File ${document.name}`} type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={(e) => setFile(e.target.files[0])} /><Button type="button" variant="secondary" onClick={upload} disabled={busy || !file}>{busy === 'upload' ? 'Upload…' : 'Carica'}</Button>{document.has_file && <Button type="button" variant="secondary" onClick={download} disabled={busy}>Scarica</Button>}<select aria-label={`Stato ${document.name}`} value={document.status} onChange={(e) => status(e.target.value)} disabled={busy}><option value="requested">Richiesto</option><option value="uploaded" disabled={!document.has_file}>Caricato</option><option value="verified" disabled={!document.has_file}>Verificato</option><option value="rejected" disabled={!document.has_file}>Rifiutato</option></select></div>{error && <small className="field-error" role="alert">{error}</small>}</article>
}

export function PracticePage() {
  const { id } = useParams(); const [state, setState] = useState({ loading: true, data: null, error: null }); const [documentName, setDocumentName] = useState(''); const [note, setNote] = useState(''); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState(''); const [actionError, setActionError] = useState('')
  const load = useCallback(async () => { try { setState({ loading: false, data: await getPractice(id), error: null }) } catch (error) { setState({ loading: false, data: null, error }) } }, [id])
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer) }, [load])
  async function addDocument(e) { e.preventDefault(); setBusy('document'); setNotice(''); setActionError(''); try { await requestDocument(id, documentName); setDocumentName(''); await load(); setNotice('Documento richiesto.') } catch (error) { setActionError(error.message) } finally { setBusy('') } }
  async function addNote(e) { e.preventDefault(); setBusy('note'); setNotice(''); setActionError(''); try { await addPracticeNote(id, note); setNote(''); await load(); setNotice('Nota pratica aggiunta.') } catch (error) { setActionError(error.message) } finally { setBusy('') } }
  if (state.loading) return <LoadingState label="Caricamento pratica…" />
  if (state.error) return <ErrorState message={state.error.message} onRetry={load} />
  const practice = state.data
  return <><PageHeader eyebrow={`Pratica #${practice.id}`} title="Gestione pratica" description={`Aperta ${formatDateTime(practice.opened_at)}`} actions={<Badge tone="violet">{humanize(practice.status)}</Badge>} />{notice && <div className="alert alert-success" role="status">{notice}</div>}{actionError && <div className="alert alert-error" role="alert">{actionError}</div>}<div className="practice-grid"><Card className="action-card"><h3>Richiedi documento</h3><form onSubmit={addDocument}><label><span>Nome documento</span><input value={documentName} onChange={(e) => setDocumentName(e.target.value)} required /></label><Button type="submit" disabled={busy || !documentName.trim()}>{busy === 'document' ? 'Invio…' : 'Aggiungi richiesta'}</Button></form></Card><Card className="action-card"><h3>Nota pratica</h3><form onSubmit={addNote}><label><span>Testo nota</span><textarea value={note} onChange={(e) => setNote(e.target.value)} required /></label><Button type="submit" disabled={busy || !note.trim()}>{busy === 'note' ? 'Salvataggio…' : 'Aggiungi nota'}</Button></form></Card></div><Card className="documents-card"><div className="detail-card-heading"><h2>Documenti</h2></div><div>{practice.documents?.length ? practice.documents.map((doc) => <DocumentRow key={doc.id} document={doc} onChanged={load} />) : <p className="muted-copy">Nessun documento richiesto.</p>}</div></Card><Card className="practice-notes"><div className="detail-card-heading"><h2>Note pratica</h2></div>{practice.notes?.length ? practice.notes.map((item) => <article key={item.id}><strong>{item.author?.name || 'Utente CRM'}</strong><p>{item.body}</p><time>{formatDateTime(item.created_at)}</time></article>) : <p className="muted-copy practice-empty-copy">Nessuna nota pratica.</p>}</Card></>
}
