import { useCallback, useEffect, useState } from 'react'
import { createOrigin, deleteOrigin, getAdminUsers, getOrigin, getOrigins, updateOrigin, updateOriginOperators } from '../../api/admin'
import { ApiError } from '../../api/client'
import { Badge } from '../../components/common/Badge'
import { Button } from '../../components/common/Button'
import { Card } from '../../components/common/Card'
import { DataTable } from '../../components/common/DataTable'
import { PageHeader } from '../../components/common/PageHeader'
import { ConfirmDialog } from '../../components/feedback/ConfirmDialog'
import { ErrorState } from '../../components/feedback/ErrorState'
import { LoadingState } from '../../components/feedback/LoadingState'

function OriginDialog({ item, open, onClose, onSaved }) {
  const [values, setValues] = useState({ code: '', name: '', active: true }); const [errors, setErrors] = useState({}); const [saving, setSaving] = useState(false)
  useEffect(() => { if (!open) return undefined; const timer = setTimeout(() => { setValues(item ? { code: item.code, name: item.name, active: item.active } : { code: '', name: '', active: true }); setErrors({}) }, 0); return () => clearTimeout(timer) }, [item, open])
  if (!open) return null
  function change(event) { const { name, value, checked, type } = event.target; setValues((current) => ({ ...current, [name]: type === 'checkbox' ? checked : value })) }
  async function submit(event) { event.preventDefault(); setSaving(true); setErrors({}); try { if (item) await updateOrigin(item.id, values); else await createOrigin(values); await onSaved(); onClose() } catch (error) { if (error instanceof ApiError) setErrors(error.fieldErrors) } finally { setSaving(false) } }
  return <div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-labelledby="origin-title" onSubmit={submit}><h2 id="origin-title">{item ? 'Modifica provenienza' : 'Nuova provenienza'}</h2><div className="admin-form-grid"><label><span>Codice</span><input name="code" value={values.code} onChange={change} required />{errors.code && <small className="field-error">{errors.code[0]}</small>}</label><label><span>Nome</span><input name="name" value={values.name} onChange={change} required />{errors.name && <small className="field-error">{errors.name[0]}</small>}</label><label className="checkbox-field"><input name="active" type="checkbox" checked={values.active} onChange={change} /><span>Provenienza attiva</span></label></div><div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>Annulla</Button><Button type="submit" disabled={saving}>{saving ? 'Salvataggio…' : 'Salva'}</Button></div></form></div>
}

function OperatorsDialog({ origin, open, onClose, onSaved }) {
  const [rows, setRows] = useState([]); const [state, setState] = useState({ loading: true, saving: false, error: '' })
  useEffect(() => { if (!open) return undefined; let active = true; const timer = setTimeout(() => { Promise.all([getOrigin(origin.id), getAdminUsers()]).then(([detail, users]) => { if (!active) return; const associated = new Map((detail.operators || []).map((item) => [item.id, item])); setRows(users.filter((user) => user.role === 'operator' && user.active).map((user, index) => ({ user_id: user.id, name: user.name, included: associated.has(user.id), receives_leads: associated.get(user.id)?.receives_leads ?? true, sort_order: associated.get(user.id)?.sort_order ?? index }))); setState({ loading: false, saving: false, error: '' }) }).catch((error) => active && setState({ loading: false, saving: false, error: error.message })) }, 0); return () => { active = false; clearTimeout(timer) } }, [open, origin])
  if (!open) return null
  function change(id, field, value) { setRows((current) => current.map((row) => row.user_id === id ? { ...row, [field]: value } : row)) }
  async function submit(event) { event.preventDefault(); setState((current) => ({ ...current, saving: true, error: '' })); try { await updateOriginOperators(origin.id, rows.filter((row) => row.included).map(({ user_id, receives_leads, sort_order }) => ({ user_id, receives_leads, sort_order: Number(sort_order) }))); await onSaved(); onClose() } catch (error) { setState((current) => ({ ...current, saving: false, error: error.message })) } }
  const receivers = rows.filter((row) => row.included && row.receives_leads).length
  return <div className="modal-backdrop"><form className="modal operators-modal" role="dialog" aria-modal="true" aria-labelledby="operators-title" onSubmit={submit}><h2 id="operators-title">Operatori · {origin.name}</h2><p>Seleziona associazione, ricezione lead e priorità round-robin.</p>{state.error && <div className="alert alert-error">{state.error}</div>}{state.loading ? <LoadingState /> : <div className="operator-config-list">{rows.map((row) => <div key={row.user_id}><label className="checkbox-field"><input type="checkbox" checked={row.included} onChange={(event) => change(row.user_id, 'included', event.target.checked)} /><span>{row.name}</span></label><label className="checkbox-field"><input type="checkbox" checked={row.receives_leads} disabled={!row.included} onChange={(event) => change(row.user_id, 'receives_leads', event.target.checked)} /><span>Riceve lead</span></label><label><span>Ordine</span><input type="number" value={row.sort_order} disabled={!row.included} onChange={(event) => change(row.user_id, 'sort_order', event.target.value)} /></label></div>)}</div>}{!state.loading && receivers === 0 && <div className="alert alert-warning" role="alert">Nessun operatore configurato per ricevere lead: i nuovi ingressi resteranno non assegnati.</div>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>Annulla</Button><Button type="submit" disabled={state.loading || state.saving}>{state.saving ? 'Salvataggio…' : 'Salva operatori'}</Button></div></form></div>
}

export function AdminOriginsPage() {
  const [state, setState] = useState({ loading: true, data: [], error: null }); const [dialog, setDialog] = useState({ open: false, item: null }); const [operators, setOperators] = useState(null); const [deleting, setDeleting] = useState(null); const [deleteBusy, setDeleteBusy] = useState(false); const [feedback, setFeedback] = useState({ message: '', type: 'success' })
  const load = useCallback(async () => { try { setState({ loading: false, data: await getOrigins(), error: null }) } catch (error) { setState({ loading: false, data: [], error }) } }, [])
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer) }, [load])
  async function saved(message = 'Provenienza salvata.') { await load(); setFeedback({ message, type: 'success' }) }
  async function remove() { setDeleteBusy(true); try { await deleteOrigin(deleting.id); setDeleting(null); await saved('Provenienza eliminata.') } catch (error) { setDeleting(null); setFeedback({ message: error.message, type: 'error' }) } finally { setDeleteBusy(false) } }
  const columns = [{ key: 'name', label: 'Provenienza', render: (i) => <div className="table-primary"><strong>{i.name}</strong><span>{i.code}</span></div> }, { key: 'active', label: 'Stato', render: (i) => <Badge tone={i.active ? 'success' : 'danger'}>{i.active ? 'Attiva' : 'Disattivata'}</Badge> }, { key: 'operators', label: 'Distribuzione', render: (i) => { const enabled = (i.operators || []).filter((op) => op.receives_leads).length; return enabled ? `${enabled} ricevono lead` : <Badge tone="danger">Nessun ricevente</Badge> } }, { key: 'actions', label: 'Azioni', render: (i) => <div className="inline-actions"><Button variant="secondary" onClick={() => setOperators(i)}>Operatori</Button><Button variant="secondary" onClick={() => setDialog({ open: true, item: i })}>Modifica</Button><Button variant="danger" onClick={() => setDeleting(i)}>Elimina</Button></div> }]
  return <><PageHeader eyebrow="Distribuzione" title="Provenienze" description="Configura canali commerciali e operatori che ricevono lead." actions={<Button onClick={() => setDialog({ open: true, item: null })}>Nuova provenienza</Button>} />{feedback.message && <div className={`alert alert-${feedback.type}`} role={feedback.type === 'error' ? 'alert' : 'status'}>{feedback.message}</div>}{state.loading ? <LoadingState /> : state.error ? <ErrorState message={state.error.message} onRetry={load} /> : <Card className="admin-table-card"><DataTable columns={columns} rows={state.data} emptyTitle="Nessuna provenienza" /></Card>}<OriginDialog {...dialog} onClose={() => setDialog({ open: false, item: null })} onSaved={saved} /><OperatorsDialog origin={operators} open={Boolean(operators)} onClose={() => setOperators(null)} onSaved={() => saved('Operatori aggiornati.')} /><ConfirmDialog open={Boolean(deleting)} busy={deleteBusy} title="Elimina provenienza" message="La provenienza può essere eliminata solo se non è mai stata utilizzata." confirmLabel="Elimina" onClose={() => setDeleting(null)} onConfirm={remove} /></>
}
