import { useCallback, useEffect, useState } from 'react'
import { assignRecycle, getAdminUsers, getOrigin, getOrigins, getRecycles } from '../../api/admin'
import { Badge } from '../../components/common/Badge'
import { Button } from '../../components/common/Button'
import { Card } from '../../components/common/Card'
import { DataTable } from '../../components/common/DataTable'
import { PageHeader } from '../../components/common/PageHeader'
import { Pagination } from '../../components/common/Pagination'
import { StatusBadge } from '../../components/common/StatusBadge'
import { ErrorState } from '../../components/feedback/ErrorState'
import { LoadingState } from '../../components/feedback/LoadingState'
import { formatDateTime } from '../../utils/formatters'

const EMPTY = { origin: '', current_operator: '', previous_operator: '', unassigned: '', date_from: '', date_to: '', per_page: '20' }

function ReassignDialog({ recycle, onClose, onSaved }) {
  const [operators, setOperators] = useState([]); const [selected, setSelected] = useState(''); const [state, setState] = useState({ loading: true, saving: false, error: '' })
  useEffect(() => { let active = true; const timer = setTimeout(() => getOrigin(recycle.origin.id).then((origin) => { if (!active) return; const list = (origin.operators || []).filter((item) => item.active && item.receives_leads); setOperators(list); setSelected(String(recycle.current_operator?.id || list[0]?.id || '')); setState({ loading: false, saving: false, error: '' }) }).catch((error) => active && setState({ loading: false, saving: false, error: error.message })), 0); return () => { active = false; clearTimeout(timer) } }, [recycle])
  async function submit(event) { event.preventDefault(); setState((current) => ({ ...current, saving: true, error: '' })); try { await assignRecycle(recycle.cycle_id, selected); await onSaved(); onClose() } catch (error) { setState((current) => ({ ...current, saving: false, error: error.message })) } }
  return <div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-labelledby="recycle-title" onSubmit={submit}><h2 id="recycle-title">Riassegna ricircolo</h2><p>Solo operatori eleggibili per {recycle.origin.name}.</p>{state.error && <div className="alert alert-error">{state.error}</div>}{state.loading ? <LoadingState /> : <label className="dialog-field"><span>Operatore</span><select value={selected} onChange={(event) => setSelected(event.target.value)}>{operators.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>Annulla</Button><Button type="submit" disabled={state.loading || state.saving || !selected}>{state.saving ? 'Salvataggio…' : 'Riassegna'}</Button></div></form></div>
}

export function AdminRecyclesPage() {
  const [draft, setDraft] = useState(EMPTY); const [query, setQuery] = useState({ ...EMPTY, page: 1 }); const [options, setOptions] = useState({ origins: [], users: [] }); const [state, setState] = useState({ loading: true, data: [], meta: {}, error: null }); const [selected, setSelected] = useState(null); const [notice, setNotice] = useState('')
  const load = useCallback(async () => { setState((c) => ({ ...c, loading: true, error: null })); try { const [result, origins, users] = await Promise.all([getRecycles(query), getOrigins(), getAdminUsers()]); setOptions({ origins: origins.filter((i) => i.active), users: users.filter((i) => i.role === 'operator') }); setState({ loading: false, data: result.data, meta: result.meta, error: null }) } catch (error) { setState({ loading: false, data: [], meta: {}, error }) } }, [query])
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer) }, [load])
  const columns = [{ key: 'client', label: 'Cliente', render: (i) => <div className="table-primary"><strong>{i.lead.contact.first_name} {i.lead.contact.last_name}</strong><span>Lead #{i.lead.id}</span></div> }, { key: 'origin', label: 'Provenienza', render: (i) => i.origin.name }, { key: 'reentered_at', label: 'Data rientro', render: (i) => formatDateTime(i.reentered_at) }, { key: 'previous_operator', label: 'Precedente', render: (i) => i.previous_operator?.name || '—' }, { key: 'current_operator', label: 'Corrente', render: (i) => i.current_operator?.name || <Badge tone="danger">Non assegnato</Badge> }, { key: 'previous_outcome', label: 'Esito precedente', render: (i) => i.previous_outcome ? <StatusBadge status={i.previous_outcome} /> : '—' }, { key: 'recycle_count', label: 'Ricircoli', render: (i) => <Badge tone="violet">x{i.recycle_count}</Badge> }, { key: 'actions', label: 'Azioni', render: (i) => <Button variant="secondary" disabled={!i.can_reassign} onClick={() => setSelected(i)}>Riassegna</Button> }]
  function change(event) { setDraft((c) => ({ ...c, [event.target.name]: event.target.value })) }
  return <><PageHeader eyebrow="Amministrazione" title="Ricircoli" description="Controlla i lead rientrati e la loro assegnazione corrente." />{notice && <div className="alert alert-success">{notice}</div>}<Card className="filters-card"><form onSubmit={(e) => { e.preventDefault(); setQuery({ ...draft, page: 1 }) }}><label><span>Provenienza</span><select name="origin" value={draft.origin} onChange={change}><option value="">Tutte</option>{options.origins.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label><span>Operatore corrente</span><select name="current_operator" value={draft.current_operator} onChange={change}><option value="">Tutti</option>{options.users.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label><span>Operatore precedente</span><select name="previous_operator" value={draft.previous_operator} onChange={change}><option value="">Tutti</option>{options.users.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label><span>Assegnazione</span><select name="unassigned" value={draft.unassigned} onChange={change}><option value="">Tutti</option><option value="1">Non assegnati</option><option value="0">Assegnati</option></select></label><label><span>Dal</span><input type="date" name="date_from" value={draft.date_from} onChange={change} /></label><label><span>Al</span><input type="date" name="date_to" value={draft.date_to} onChange={change} /></label><div className="filter-actions"><Button type="submit">Applica filtri</Button></div></form></Card>{state.loading ? <LoadingState /> : state.error ? <ErrorState message={state.error.message} onRetry={load} /> : <Card className="admin-table-card"><DataTable columns={columns} rows={state.data} rowKey="cycle_id" emptyTitle="Nessun ricircolo" /><Pagination meta={state.meta} onPageChange={(page) => setQuery((c) => ({ ...c, page }))} /></Card>}{selected && <ReassignDialog recycle={selected} onClose={() => setSelected(null)} onSaved={async () => { await load(); setNotice('Ricircolo riassegnato.') }} />}</>
}
